# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: xcart/ruby:2.4.1-jekyll
    environment:
          JEKYLL_DESTINATION: _site
          CI_WORKSPACE: _workspace
          SSH_STRING: ssh -o StrictHostKeyChecking=no -p1002
          SSH_HOST: kbsync@kb5.x-cart.com
          SSH_HOST_RU: kbsync@kb5.x-cart.com
          # SSH_HOST_RU: kbsync@95.181.198.245
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --jobs=4 --retry=3 --path=vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: rm -rf _workspace _site
      - run: mkdir -p _workspace/build-targets
      - run: mkdir -p _workspace/artifacts

      - run: ./get_targets.sh _workspace/build-targets

      - run: 
          name: Building devs en (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/devs_en ]; then
              ./build.sh devs_en
              rsync -azivchu -e "$SSH_STRING" --delete _site/devs_en/ "$SSH_HOST:/www/kbsync/devs_en" | egrep -v "^\."
            fi

      - run: 
          name: Building devs ru (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/devs_ru ]; then
              ./build.sh devs_ru
              rsync -azivchu -e "$SSH_STRING" --delete _site/devs_ru/ "$SSH_HOST_RU:/www/kbsync/devs_ru" | egrep -v "^\."
            fi

      - run: 
          name: Building kb en (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/kb_en ]; then
              ./build.sh kb_en
              rsync -azivchu -e "$SSH_STRING" --delete _site/kb_en/ "$SSH_HOST:/www/kbsync/kb_en" | egrep -v "^\."
            fi

      - run: 
          name: Building kb ru (if needed)
          command: |
            if [ -f ~/repo/_workspace/build-targets/kb_ru ]; then
              ./build.sh kb_ru
              rsync -azivchu -e "$SSH_STRING" --delete _site/kb_ru/ "$SSH_HOST_RU:/www/kbsync/kb_ru" | egrep -v "^\."
            fi

